#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#
# Filesystem encryption, etc
#
# License
# =======
#
# Copyright (C) 2014-2016 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

TOMB_REPO="https://github.com/dyne/Tomb"
TOMB_COMMIT='c80ebd6d6ed77980eb5b559757e03ea13a29bdd1'

function mesh_install_tomb {
    chroot ${rootdir} apt-get -y install cryptsetup zsh pinentry-curses

    if [ ! -d ${rootdir}/$INSTALL_DIR ]; then
        mkdir -p ${rootdir}/$INSTALL_DIR
    fi

    git_clone $TOMB_REPO ${rootdir}/$INSTALL_DIR/tomb
    cd ${rootdir}/$INSTALL_DIR/tomb

    git checkout $TOMB_COMMIT -b $TOMB_COMMIT

    chroot ${rootdir} /bin/bash -x <<EOF
cd $INSTALL_DIR/tomb
make install
EOF
    if [ ! -f ${rootdir}/usr/local/bin/tomb ]; then
        exit 93462
    fi
}

function install_tomb {
    if [ $INSTALLING_MESH ]; then
        mesh_install_tomb
        return
    fi

    function_check set_repo_commit
    set_repo_commit $INSTALL_DIR/tomb "tomb commit" "$TOMB_COMMIT" $TOMB_REPO

    if [ -f $COMPLETION_FILE ]; then
        if grep -Fxq "install_tomb" $COMPLETION_FILE; then
            return
        fi
    fi

    apt-get -y install cryptsetup zsh pinentry-curses

    if [ ! -d $INSTALL_DIR ]; then
        mkdir -p $INSTALL_DIR
    fi

    git_clone $TOMB_REPO $INSTALL_DIR/tomb
    cd $INSTALL_DIR/tomb

    git checkout $TOMB_COMMIT -b $TOMB_COMMIT
    if ! grep -q "tomb commit" $COMPLETION_FILE; then
        echo "tomb commit:$TOMB_COMMIT" >> $COMPLETION_FILE
    else
        sed -i "s/tomb commit.*/tomb commit:$TOMB_COMMIT/g" $COMPLETION_FILE
    fi

    make install
    if [ ! -f /usr/local/bin/tomb ]; then
        exit 93462
    fi

    echo 'install_tomb' >> $COMPLETION_FILE
}

# NOTE: deliberately no exit 0
