#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#

# Removes a mailing list to the email configuration

# License
# =======
#
# Copyright (C) 2015 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='freedombone'

export TEXTDOMAIN=$PROJECT_NAME
export TEXTDOMAINDIR="/usr/share/locale"

MYUSERNAME=$USER
MAILINGLIST=
LIST_ADDRESS=

function show_help {
    echo ''
    echo $'freedombone-rmlist -u [username] -l [mailing list name] -e [list email address]'
    echo ''
    exit 0
}

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--help)
    show_help
    ;;
    -u|--user)
    shift
    MYUSERNAME="$1"
    ;;
    -l|--list)
    shift
    MAILINGLIST="$1"
    ;;
    -e|--email)
    shift
    LIST_ADDRESS="$1"
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

if ! [[ $MYUSERNAME && $MAILINGLIST ]]; then
    show_help
fi

MUTTRC=/home/$MYUSERNAME/.muttrc
MUTT_MAILBOXES=$(grep "mailboxes =" $MUTTRC)
if [[ $MUTT_MAILBOXES == *$MAILINGLIST* ]]; then
    sed -i "s| =$MAILINGLIST||g" $MUTTRC
    chown $MYUSERNAME:$MYUSERNAME $MUTTRC
fi

if [ $LIST_ADDRESS ]; then
    if ! grep -q "unsubscribe $LIST_ADDRESS" $MUTTRC; then
        sed -i "s|subscribe $LIST_ADDRESS|unsubscribe $LIST_ADDRESS|g" $MUTTRC
    fi
fi

exit 0
