#!/bin/bash
#  _____               _           _
# |   __|___ ___ ___ _| |___ _____| |_ ___ ___ ___
# |   __|  _| -_| -_| . | . |     | . | . |   | -_|
# |__|  |_| |___|___|___|___|_|_|_|___|___|_|_|___|
#
#                              Freedom in the Cloud
#
# Handling installation of snap packages
#
# License
# =======
#
# Copyright (C) 2018 Bob Mottram <bob@freedombone.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function install_snap {
    snap_package="$1"

    if [ ! "$snap_package" ]; then
        echo $'No snap package was specified'
        exit 257625472
    fi
    no_of_snaps=$(df | grep -c "/snap/core/")
    if [ "$no_of_snaps" -eq 0 ]; then
        $INSTALL_PACKAGES snapd
    fi
    if ! snap install "$snap_package"; then
        echo $"Failed to install snap package $snap_package"
        exit 46382854
    fi
}

function remove_snap {
    snap_package="$1"

    if [ ! "$snap_package" ]; then
        echo $'No snap package was specified'
        exit 45332485421
    fi

    snap remove "$snap_package"

    no_of_snaps=$(df | grep -c "/snap/")
    if [ "$no_of_snaps" -eq 1 ]; then
        $REMOVE_PACKAGES snapd
    fi
}

# NOTE: deliberately no exit 0
