#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#

# Adds an xmpp user

# License
# =======
#
# Copyright (C) 2015 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='freedombone'

export TEXTDOMAIN=${PROJECT_NAME}-addxmpp
export TEXTDOMAINDIR="/usr/share/locale"

EMAIL_ADDRESS=
NEW_USER_PASSWORD=

function show_help {
    echo ''
    echo $'freedombone-addxmpp -e [email address] -p [password]'
    echo ''
    exit 0
}

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--help)
    show_help
    ;;
    -e|--email)
    shift
    EMAIL_ADDRESS="$1"
    ;;
    -p|--password|--passphrase)
    shift
    NEW_USER_PASSWORD="$1"
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

if [ ! -d /etc/prosody ]; then
    echo $'xmpp server is not installed'
    exit 0
fi

if [ ! $EMAIL_ADDRESS ]; then
    show_help
    exit 1
fi

if [ ! $NEW_USER_PASSWORD ]; then
    prosodyctl adduser $EMAIL_ADDRESS
else
    USERNAME=$(echo $EMAIL_ADDRESS | awk -F '@' '{print $1}')
    DOMAIN_NAME=$(echo $EMAIL_ADDRESS | awk -F '@' '{print $2}')
    prosodyctl register $USERNAME $DOMAIN_NAME "$NEW_USER_PASSWORD"
    if [ ! "$?" = "0" ]; then
        exit 2
    fi
fi

exit 0
