#!/bin/bash
#  _____               _           _
# |   __|___ ___ ___ _| |___ _____| |_ ___ ___ ___
# |   __|  _| -_| -_| . | . |     | . | . |   | -_|
# |__|  |_| |___|___|___|___|_|_|_|___|___|_|_|___|
#
#                              Freedom in the Cloud
#
# Install daemon for the web admin system
# See also freedombone-utils-webadmin
#
# License
# =======
#
# Copyright (C) 2018 Bob Mottram <bob@freedombone.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='freedombone'

export TEXTDOMAIN=${PROJECT_NAME}-installer
export TEXTDOMAINDIR="/usr/share/locale"

CONFIGURATION_FILE="/root/${PROJECT_NAME}.cfg"

local_hostname=$(grep 'host-name' /etc/avahi/avahi-daemon.conf | awk -F '=' '{print $2}').local

pending_removes="/var/www/${local_hostname}/htdocs/admin/pending_removes.txt"
pending_installs="/var/www/${local_hostname}/htdocs/admin/pending_installs.txt"

while true
do
    if [ -f /tmp/.upgrading ]; then
        sleep 2
    else
        if [ -f "$pending_installs" ]; then
            linestr=$(head -n 1 "$pending_installs")
            if [[ "$linestr" == "install_"* ]]; then
                app_name=$(echo "$linestr" | awk -F '_' '{print $2}' | awk -F ',' '{print $1}')
                if [ -f "/usr/share/${PROJECT_NAME}/apps/${PROJECT_NAME}-app-${app_name}" ]; then
                    app_domain=$(echo "$linestr" | awk -F ',' '{print $2}')
                    app_name_upper=$(echo "$app_name" | awk '{print toupper($0)}')
                    freedns_code=$(echo "$linestr" | awk -F ',' '{print $3}')

                    # indicate that we are installing
                    if [[ "$linestr" != *'_running'* ]]; then
                        sed -i "s|${app_name}|${app_name}_running|g" "$pending_installs"
                    fi

                    # Add domain name to the config
                    if ! grep -q "${app_name_upper}_DOMAIN_NAME=" $CONFIGURATION_FILE; then
                        echo "${app_name_upper}_DOMAIN_NAME=${app_domain}" >> $CONFIGURATION_FILE
                    else
                        sed -i "s|${app_name_upper}_DOMAIN_NAME=.*|${app_name_upper}_DOMAIN_NAME=${app_domain}|g" $CONFIGURATION_FILE
                    fi

                    # Add freedns code to the config
                    if [ "$freedns_code" ]; then
                        # shellcheck disable=SC2086
                        ${app_name_upper}_CODE="${freedns_code}"

                        if ! grep -q "${app_name_upper}_CODE=" $CONFIGURATION_FILE; then
                            echo "${app_name_upper}_CODE=${freedns_code}" >> $CONFIGURATION_FILE
                        else
                            sed -i "s|${app_name_upper}_CODE=.*|${app_name_upper}_CODE=${freedns_code}|g" $CONFIGURATION_FILE
                        fi
                    fi

                    /usr/local/bin/${PROJECT_NAME}-addremove add "${app_name}"
                fi
                # remove the line
                sed -i "/$linestr/d" "$pending_installs"
            else
                # if any unusual line is found then remove the file
                rm "$pending_installs"
            fi
        fi

        sleep 1

        if [ -f "$pending_removes" ]; then
            linestr=$(head -n 1 "$pending_removes")
            if [[ "$linestr" == "remove_"* ]]; then
                app_name=$(echo "$linestr" | awk -F '_' '{print $2}')
                if [ -f "/usr/share/${PROJECT_NAME}/apps/${PROJECT_NAME}-app-${app_name}" ]; then
                    # indicate that we are removing
                    if [[ "$linestr" != *'_running'* ]]; then
                        sed -i "s|${app_name}|${app_name}_running|g" "$pending_removes"
                    fi
                    /usr/local/bin/${PROJECT_NAME}-addremove remove "${app_name}"
                fi
                # remove the line
                sed -i "/$linestr/d" "$pending_removes"
            else
                # if any unusual line is found then remove the file
                rm "$pending_removes"
            fi
        fi

        sleep 1
    fi
done

exit 0
