#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#
# Command to upgrade the system

# License
# =======
#
# Copyright (C) 2015 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

FREEDOMBONE_REPO="https://github.com/bashrc/freedombone"

update-ca-certificates

if [ ! -d /root/freedombone ]; then
  echo "    git clone $FREEDOMBONE_REPO /root/freedombone"
fi

if [ -f /root/freedombone.cfg ]; then
    cd /root/freedombone
    git stash
    git pull
    make install
    freedombone -c /root/freedombone.cfg
fi

echo '

' | reset-tripwire

# deliberately there is no 'exit 0' here
