#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#
# Show help
#
# License
# =======
#
# Copyright (C) 2014-2016 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

function show_help {
    echo ''
    echo $"${PROJECT_NAME} -c [configuration file]"
    echo ''
    echo $'  -h --help             Show help'
    echo $'     menuconfig         Easy interactive installation'
    echo $'     menuconfig-full    Full interactive installation'
    echo $'     menuconfig-onion   Interactive installation for onion-only sites'
    echo $'  -c --config           Installing from a configuration file'
    echo $'     --bbb              Installing on Beaglebone Black'
    echo $'  -u --user             User to install the system as'
    echo $'  -d --domain           Default domain name'
    echo $'  -s --system           System type'
    echo $'     --ip               Static LAN IP address of the system'
    echo $'     --iprouter         LAN IP address of the internet router'
    echo $'     --ddns             Dynamic DNS provider domain'
    echo $'     --ddnsuser         Dynamic DNS provider username'
    echo $'     --ddnspass         Dynamic DNS provider password'
    echo ''
    echo $'     --microblogdomain  Microblog domain name'
    echo $'     --wikidomain       Wiki domain name'
    echo $'     --blogdomain       Blog domain name'
    echo $'     --hubzilladomain   Hubzilla domain name'
    echo $'     --gitdomain        Git hosting domain name'
    echo $'  -t --time             Domain used as a TLS time source'
    echo $'     --ssh              ssh port number'
    echo $'     --list             Public mailing list name'
    echo $'     --cores            Number of CPU cores'
    echo $'     --name             Your name'
    echo $'     --email            Your email address'
    echo $'     --usb              Path for the USB drive (eg. /dev/sdb1)'
    echo $'     --vpass            Mumble server password'
    echo $'     --vport            Mumble server port'
    echo $'     --ns1              First DNS nameserver'
    echo $'     --ns2              Second DNS nameserver'
    echo $'     --repo             Debian repository'
    echo ''
    echo 'Possible variants are:'
    show_available_variants
    exit 0
}

# NOTE: deliberately no exit 0
