#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#
# Visit ipfs sites by entering a username
#
# License
# =======
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='freedombone'

export TEXTDOMAIN=${PROJECT_NAME}-mesh-visit-site
export TEXTDOMAINDIR="/usr/share/locale"

IPFS_URL='http://127.0.0.1:8080/ipns'

# The browser application to use
BROWSER=midori

# An optional suffix to be appended to the URL
SUFFIX=$1

IPFS_USERS_FILE=/home/$USER/.ipfs-users
if [ ! -f $IPFS_USERS_FILE ]; then
    exit 0
fi
USERS_FILE=/home/$USER/Users.txt
if [ ! -f $USERS_FILE ]; then
    exit 0
fi

data=$(tempfile 2>/dev/null)
trap "rm -f $data" 0 1 2 5 15
dialog --title $"Visit IPFS site" \
    --backtitle $"Freedombone mesh" \
    --inputbox $"Enter the username or Tox ID for the site you wish to visit" 8 70 2>$data
sel=$?
case $sel in
    0)
        TOX_USERNAME_OR_ID=$(<$data)
        if [ ${#TOX_USERNAME_OR_ID} -gt 0 ]; then
            if ! grep -q "$TOX_USERNAME_OR_ID" $USERS_FILE; then
                TOX_ID="$TOX_USERNAME_OR_ID"
            else
                TOX_ID=$(cat "$USERS_FILE" | grep "$TOX_USERNAME_OR_ID" | head -n 1 | sed "s|$TOX_USERNAME_OR_ID ||g" | sed -e 's/^[[:space:]]*//')
            fi

            if [ ${#TOX_ID} -gt 5 ]; then
                if ! grep -q "$TOX_ID" $IPFS_USERS_FILE; then
                    dialog --title $"Visit IPFS site" \
                           --backtitle $"Freedombone mesh" \
                           --msgbox $"An IPFS site was not found for the user '$TOX_USERNAME_OR_ID'" 8 60
                    exit 3
                fi
                IPFS_FULL_URL=${IPFS_URL}/$(cat "$IPFS_USERS_FILE" | grep $TOX_ID | head -n 1 | awk -F ':' '{print $2}')
                clear
                echo $'Opening browser. Please wait...'
                $BROWSER $IPFS_FULL_URL$SUFFIX &
            fi
        else
            exit 1
        fi
    ;;
esac

exit 0
