#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#

# Adds a mailing list to the email configuration

# License
# =======
#
# Copyright (C) 2015-2016 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

PROJECT_NAME='freedombone'

export TEXTDOMAIN=${PROJECT_NAME}-addlist
export TEXTDOMAINDIR="/usr/share/locale"

MYUSERNAME=$USER
MAILINGLIST=
SUBJECTTAG=
LIST_ADDRESS=

function show_help {
    echo ''
    echo $"${PROJECT_NAME}-addlist -u [username] -l [mailing list name] -s [subject tag] -e [list email address]"
    echo ''
    exit 0
}

while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--help)
    show_help
    ;;
    -u|--user)
    shift
    MYUSERNAME="$1"
    ;;
    -l|--list)
    shift
    MAILINGLIST="$1"
    ;;
    -s|--subject)
    shift
    SUBJECTTAG="$1"
    ;;
    -e|--email)
    shift
    LIST_ADDRESS="$1"
    ;;
    *)
    # unknown option
    ;;
esac
shift
done

if ! [[ $MYUSERNAME && $MAILINGLIST && $SUBJECTTAG ]]; then
    show_help
fi

MUTTRC=/home/$MYUSERNAME/.muttrc
PM=/home/$MYUSERNAME/.procmailrc
LISTDIR=/home/$MYUSERNAME/Maildir/$MAILINGLIST

# Exit if the list was already added
if grep -q "=$MAILINGLIST" $MUTTRC; then
    exit 54678
fi

if [ ! -d "$LISTDIR" ]; then
    mkdir -m 700 $LISTDIR
    mkdir -m 700 $LISTDIR/tmp
    mkdir -m 700 $LISTDIR/new
    mkdir -m 700 $LISTDIR/cur
fi

chown -R $MYUSERNAME:$MYUSERNAME $LISTDIR

if ! grep -q "Subject:.*()\[$SUBJECTTAG\]" $PM; then
    if ! grep -q "End of rule" $PM; then
        echo "" >> $PM
        echo "/# Email rule for $MAILINGLIST subject \[$SUBJECTTAG\]" >> $PM
        echo ":0" >> $PM
        echo "  * ^Subject:.*()\[$SUBJECTTAG\]" >> $PM
        echo "$LISTDIR/new" >> $PM
        echo "/# End of rule" >> $PM
        chown $MYUSERNAME:$MYUSERNAME $PM
    else
        sed -i "/End of rule/a
/# Email rule for $MAILINGLIST subject \[$SUBJECTTAG\]
:0
  * ^Subject:.*()\[$SUBJECTTAG\]
$LISTDIR/new
/# End of rule" $PM
    fi
fi

if [ ! -f "$MUTTRC" ]; then
    cp /etc/Muttrc $MUTTRC
    chown $MYUSERNAME:$MYUSERNAME $MUTTRC
fi

PROCMAILLOG=/home/$MYUSERNAME/log
if [ ! -d $PROCMAILLOG ]; then
    mkdir $PROCMAILLOG
    chown -R $MYUSERNAME:$MYUSERNAME $PROCMAILLOG
fi

MUTT_MAILBOXES=$(grep "mailboxes =" $MUTTRC)
if [[ $MUTT_MAILBOXES != *$MAILINGLIST* ]]; then
    sed -i "s|$MUTT_MAILBOXES|$MUTT_MAILBOXES =$MAILINGLIST|g" $MUTTRC
    chown $MYUSERNAME:$MYUSERNAME $MUTTRC
fi

if [ $LIST_ADDRESS ]; then
    sed -i "s|unsubscribe $LIST_ADDRESS|subscribe $LIST_ADDRESS|g" $MUTTRC
    if ! grep -q "subscribe $LIST_ADDRESS" $MUTTRC; then
        echo "subscribe $LIST_ADDRESS" >> $MUTTRC
    fi
fi

exit 0
