#!/bin/bash
#
# .---.                  .              .
# |                      |              |
# |--- .--. .-.  .-.  .-.|  .-. .--.--. |.-.  .-. .--.  .-.
# |    |   (.-' (.-' (   | (   )|  |  | |   )(   )|  | (.-'
# '    '     --'  --'  -' -  -' '  '   -' -'   -' '   -  --'
#
#                    Freedom in the Cloud
#
# Creates a debian image using vmdebootstrap
#
# License
# =======
#
# Copyright (C) 2015 Bob Mottram <bob@robotics.uk.to>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

IMAGE_TYPE=$1
CURR_DIR=$(pwd)
BUILD_DIR=~/.tmp_freedombone_build

rm $CURR_DIR/*.img

if [ -d $BUILD_DIR ]; then
	rm -rf $BUILD_DIR
fi
mkdir -p $BUILD_DIR
if [ -f /usr/local/bin/freedombone-image-makefile ]; then
	cp /usr/local/bin/freedombone-image-makefile $BUILD_DIR/Makefile
else
	cp /usr/bin/freedombone-image-makefile $BUILD_DIR/Makefile
fi

cp -r /etc/freedombone/* $BUILD_DIR
cd $BUILD_DIR

rm -rf vendor
mkdir vendor
if [ -d vendor/vmdebootstrap ] ; then
    (cd vendor/vmdebootstrap; git checkout .; git pull)
else
    git clone git://git.liw.fi/vmdebootstrap vendor/vmdebootstrap
fi
cd vendor/vmdebootstrap
git checkout tags/vmdebootstrap-0.8
git checkout -b tags/vmdebootstrap-0.8
for f in ../../vendor-patches/vmdebootstrap/* ; do
    echo applying $(basename $f)
    patch -p1 < $f
done

cd $BUILD_DIR
make $IMAGE_TYPE
mv build/*.bz2 $CURR_DIR
mv build/*.img $CURR_DIR
mv build/*.sig $CURR_DIR
rm -rf $BUILD_DIR

exit 0
