#!/bin/bash
#  _____               _           _
# |   __|___ ___ ___ _| |___ _____| |_ ___ ___ ___
# |   __|  _| -_| -_| . | . |     | . | . |   | -_|
# |__|  |_| |___|___|___|___|_|_|_|___|___|_|_|___|
#
#                              Freedom in the Cloud
#
# shortcuts for commands
#
# License
# =======
#
# Copyright (C) 2018 Bob Mottram <bob@freedombone.net>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

INSTALL_PACKAGES='apt-get -yq install'
INSTALL_PACKAGES_BACKPORTS='apt-get -yq -t stretch-backports install'

REMOVE_PACKAGES='apt-get -yq remove'
REMOVE_PACKAGES_PURGE='apt-get -yq remove --purge'

UPDATE_PACKAGES='apt-get -yq update'

PACKAGE_HOLD='apt-mark -q hold'
PACKAGE_UNHOLD='apt-mark -q unhold'

CLEAN_PACKAGES='apt-get clean'

# NOTE: deliberately there is no "exit 0"
